### ISSUE TITLE
mf-install is ok, but I can't do the mf-installcab

### ISSUE THREAD

**Issue by xadaisantos** [z0z0z/mf-installcab#26]
Hey guys, I need some help. The first part runs ok, but when I try the second part ("WINEPREFIX="/home/ryanj/.local/share/Steam/steamapps/compatdata/397540/pfx" ./install-mf-64.sh") it returns this:

mediafoundation
Traceback (most recent call last):
  File "installcab.py", line 318, in <module>
    output_files = extract_from_installer(cabfile, tmpdir, component)
  File "installcab.py", line 207, in extract_from_installer
    subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in _init_
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

can anyone help me please

**Comment by xadaisantos** [comment]
A more detailed explanation:
After I installed mf-install.sh, I tried this:

command 1:
PROTON="/home/xadai/.steam/steam/steamapps/common/Proton 4.11/" \ WINEPREFIX="/home/xadai/.steam/steam/steamapps/compatdata/397540/pfx" ./install-mf-64.sh -proton

output 1:
bash:  WINEPREFIX=/home/xadai/.steam/steam/steamapps/compatdata/397540/pfx: No such file or directory

command 2:
PATH=/home/xadai/.steam/steam/steamapps/common/Proton\ 5.0/dist/bin/:$PATH WINEPREFIX="/home/xadai/.steam/steam/steamapps/compatdata/397540/pfx" ./install-mf-64.sh

output 2:
mediafoundation
Traceback (most recent call last):
  File "installcab.py", line 318, in <module>
    output_files = extract_from_installer(cabfile, tmpdir, component)
  File "installcab.py", line 207, in extract_from_installer
    subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by acedogblast** [comment]
I have a similar problem but with different error output.

```
WINEPREFIX="/home/charles/WinePrefixes/BL3" PATH=/home/charles/.local/share/lutris/runners/wine/lutris-5.7-10-x86_64/bin/:$PATH ./install-mf-64.sh 
mediafoundation
windows6.1-KB976932-X64.exe: no valid cabinets found
Traceback (most recent call last):
  File "installcab.py", line 318, in <module>
    output_files = extract_from_installer(cabfile, tmpdir, component)
  File "installcab.py", line 207, in extract_from_installer
    subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['cabextract', '-F', '*mediafoundation*', '-d', '/tmp/tmpwgeTs7', 'windows6.1-KB976932-X64.exe']' returned non-zero exit status 1
```

**Comment by z0z0z** [comment]
Make sure cabextract is in your path

**Comment by Stenean** [comment]
I've faced the same problem and it turns out that the file on the Internet Archive is either broken somehow or the transfer gets interrupted and only part of the file is downloaded. After looking at [https://web.archive.org/web/20200803210804/https://download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/](https://web.archive.org/web/20200803210804/https://download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/), I've found this alternative url on microsoft site to be working and providing the full file: [http://ak.or.download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/windows6.1-KB976932-X64.exe](http://ak.or.download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/windows6.1-KB976932-X64.exe)
For completeness, here is sha256 sum of the working file:
`f4d1d418d91b1619688a482680ee032ffd2b65e420c6d2eaecf8aa3762aa64c8  windows6.1-KB976932-X64.exe`

**Comment by Micronetic** [comment]
I am getting this error when trying to install it: `./install-mf-64.sh: Zeile 32: wget: Command not found.`
The other MF install worked though (mf-install).

**Comment by z0z0z** [comment]
Install wget with your distro's package manager.
