### ISSUE TITLE
Error installing to secondary hard drive

### ISSUE THREAD

**Issue by jamiefraser77** [z0z0z/mf-installcab#28]
I run these commands:
```
cd /home/jam/mf-installcab
PROTON="/mnt/559f7880-d781-443c-9259-daf9831d710a/Steam/steamapps/common/Proton 5.13" 
WINEPREFIX="/mnt/559f7880-d781-443c-9259-daf9831d710a/Steam/steamapps/compatdata/883710/pfx" ./install-mf-64.sh
```
And get these error message - it looks like its because RE2 is installed to an external hard drive.

```
jam@jam-ncase:~/mf-installcab$ WINEPREFIX="/mnt/559f7880-d781-443c-9259-daf9831d710a/Steam/steamapps/compatdata/883710/pfx" ./install-mf-64.sh
mediafoundation
- amd64_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_fa8534ab236134c4.manifest (win64)
- wow64_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_04d9defd57c1f6bf.manifest (wow64)
- mf.dll -> /mnt/559f7880-d781-443c-9259-daf9831d710a/Steam/steamapps/compatdata/883710/pfx/drive_c/windows/syswow64
- mf.dll -> /mnt/559f7880-d781-443c-9259-daf9831d710a/Steam/steamapps/compatdata/883710/pfx/drive_c/windows/system32
- mfps.dll -> /mnt/559f7880-d781-443c-9259-daf9831d710a/Steam/steamapps/compatdata/883710/pfx/drive_c/windows/system32
Traceback (most recent call last):
  File "installcab.py", line 319, in <module>
    process_files(output_files)
  File "installcab.py", line 257, in process_files
    install_dll(file_path)
  File "installcab.py", line 231, in install_dll
    shutil.copy(dll_path, dest_dir)
  File "/usr/lib/python2.7/shutil.py", line 139, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/mnt/559f7880-d781-443c-9259-daf9831d710a/Steam/steamapps/compatdata/883710/pfx/drive_c/windows/system32/mfps.dll'
```

I've tried running the same command with `sudo` I get a lot of xyz `is not owned by you`.

Is there a work-around?

**Comment by kimamb** [comment]
Copying the folder to a path on the primary (/) drive, running the command and copying it back seems to work.
