### ISSUE TITLE
IOError: [Errno 13] Permission denied: '[...]/397540/pfx/drive_c/windows/syswow64/mf.dll'

### ISSUE THREAD

**Issue by HughPH** [z0z0z/mf-installcab#29]
Trying to install for BL3 I get this Permission denied error, I assume trying to copy mf.dll into syswow64

```
- mf.dll -> /mnt/f/steamapps/compatdata/397540/pfx/drive_c/windows/syswow64
Traceback (most recent call last):
  File "installcab.py", line 319, in <module>
    process_files(output_files)
  File "installcab.py", line 257, in process_files
    install_dll(file_path)
  File "installcab.py", line 231, in install_dll
    shutil.copy(dll_path, dest_dir)
  File "/usr/lib/python2.7/shutil.py", line 139, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/mnt/f/steamapps/compatdata/397540/pfx/drive_c/windows/syswow64/mf.dll'
```

The file exists after this error, I don't know if it should exist or not. There are no permissions issues with the file: it's -rw-rw-r-- (664)

**Comment by HughPH** [comment]
There were permission issues. I had to `chmod 777 system32` and `syswow64`
Weird

**Comment by HughPH** [comment]
So... I verified the game cache (no issues), removed the pfx directory entirely, and still it won't start - although it does recreate the pfx directory. There are no error dialog boxes.

I even removed `mfplat.dll`

This is so weird.

**Comment by HughPH** [comment]
OK, removed the `397540` directory, told Steam not to use a custom Wine version, and it launched.
I've now quit, run `install-mf-64.sh`, copied `mfplat.dll` to the folder with `Borderlands 3.exe` and ... now I get an error about D3DCommandQueue->GetClockCalibration
WTH?!
