### ISSUE TITLE
Borderlands 3 mf-installcab errors

### ISSUE THREAD

**Issue by psmgeelen** [z0z0z/mf-installcab#31]
Hi there, 

Thanks for your efforts. Your solution seems to work for most people. I have the classic "watch the monitor" lock in borderlands 3, where I need to see a movie that doesnt show (I cant see lilith either).
Your scripts come highly recommended and I followed your reddit post. mf-install works for, which is brilliant. mf-installcab fails in particular way. The print out of the terminal is:

```
(base) username@thor:~/Downloads/mf-installcab-master$ WINEPREFIX="/home/username/.local/share/Steam/steamapps/compatdata/397540/pfx" ./install-mf-64.sh 
mediafoundation
- wow64_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_04d9defd57c1f6bf.manifest (wow64)
- amd64_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_fa8534ab236134c4.manifest (win64)
- mf.dll -> /home/username/.local/share/Steam/steamapps/compatdata/397540/pfx/drive_c/windows/syswow64
- mf.dll -> /home/username/.local/share/Steam/steamapps/compatdata/397540/pfx/drive_c/windows/system32
- mfps.dll -> /home/username/.local/share/Steam/steamapps/compatdata/397540/pfx/drive_c/windows/system32
001b:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
mf
- wow64_microsoft-windows-mf_31bf3856ad364e35_6.1.7601.17514_none_b5899692ced89b37.manifest (wow64)
- amd64_microsoft-windows-mf_31bf3856ad364e35_6.1.7601.17514_none_ab34ec409a77d93c.manifest (win64)
mfreadwrite
- wow64_microsoft-windows-mfreadwrite_31bf3856ad364e35_6.1.7601.17514_none_21d097c56304ba5a.manifest (wow64)
- amd64_microsoft-windows-mfreadwrite_31bf3856ad364e35_6.1.7601.17514_none_177bed732ea3f85f.manifest (win64)
- mfreadwrite.dll -> /home/username/.local/share/Steam/steamapps/compatdata/397540/pfx/drive_c/windows/system32
- mfreadwrite.dll -> /home/username/.local/share/Steam/steamapps/compatdata/397540/pfx/drive_c/windows/syswow64
001b:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
wmadmod
- x86_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_885655287c3a2a8e.manifest (win32)
- amd64_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_e474f0ac34979bc4.manifest (win64)
- wmadmod.dll -> /home/username/.local/share/Steam/steamapps/compatdata/397540/pfx/drive_c/windows/system32
- wmadmod.dll -> /home/username/.local/share/Steam/steamapps/compatdata/397540/pfx/drive_c/windows/syswow64
001b:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
wmvdecod
- x86_microsoft-windows-wmvdecod_31bf3856ad364e35_6.1.7601.17514_none_c491ee3d3e923b78.manifest (win32)
- amd64_microsoft-windows-wmvdecod_31bf3856ad364e35_6.1.7601.17514_none_20b089c0f6efacae.manifest (win64)
- wmvdecod.dll -> /home/username/.local/share/Steam/steamapps/compatdata/397540/pfx/drive_c/windows/syswow64
- wmvdecod.dll -> /home/username/.local/share/Steam/steamapps/compatdata/397540/pfx/drive_c/windows/system32
001b:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
wmadmod
- x86_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_885655287c3a2a8e.manifest (win32)
- amd64_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_e474f0ac34979bc4.manifest (win64)
- wmadmod.dll -> /home/username/.local/share/Steam/steamapps/compatdata/397540/pfx/drive_c/windows/system32
- wmadmod.dll -> /home/username/.local/share/Steam/steamapps/compatdata/397540/pfx/drive_c/windows/syswow64
001b:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
-e 
Now you need to get mfplat.dll in your application directory
```
I run Borderlands 3 on Ubuntu 20.10, with Steam, on Proton 5.13 (other versions of proton didnt work me). I had to install vulkan-tools, wine and winetricks to get as far as I have. Naturally I have placed the mfplat.dll in the directory as displayed in your youtube clip. I noticed that some other users had to replace the mfplat.dll; In my directory of the game there was nothing to replace it with, so I just copied it. 

What to do?

**Comment by z0z0z** [comment]
- Delete (backup if you want) the Wine prefix for the game i.e. this folder:
**/home/username/.local/share/Steam/steamapps/compatdata/397540**
- Start the game again in Steam to generate a new prefix and close it
- Try **one** of the fixes, either mf-install **or** mf-installcab. If it doesn't work, repeat steps one and two but try the other.

**Comment by psmgeelen** [comment]
I completely reinstalled steam and now it seam to work out-of-the-box with Proton 5.21 GE. Now it broken during the loading process.. I think something more is wrong..

**Comment by dukenukemx** [comment]
I too am having issues with Borderlands 3 and getting stuck at "watch the monitor".  I'm using Proton-6.1-GE-2 on Linux Mint 20.  I'm using it on Epic version.

**Comment by Wurzelmann** [comment]
For me it won't work because of the symlinked DLLs (Proton > 5.13):

```
mediafoundation
- amd64_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_fa8534ab236134c4.manifest (win64)
- wow64_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_04d9defd57c1f6bf.manifest (wow64)
- mf.dll -> /games/steam/steamapps/compatdata/397540/pfx/drive_c/windows/syswow64
Traceback (most recent call last):
  File "installcab.py", line 319, in <module>
    process_files(output_files)
  File "installcab.py", line 257, in process_files
    install_dll(file_path)
  File "installcab.py", line 231, in install_dll
    shutil.copy(dll_path, dest_dir)
  File "/usr/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/games/steam/steamapps/compatdata/397540/pfx/drive_c/windows/syswow64/mf.dll'
```

**Comment by z0z0z** [comment]
@Wurzelmann Yeah back when Proton 5.13 came out I just changed `rm -r` to `rm -rf` to overwrite symlinks.

I never edited the python script used in this though.

**Comment by Wurzelmann** [comment]
Thank you very much for this! In the meantime, I tried [mf-fix](https://github.com/HoodedDeath/mf-fix), which is based on your script and it worked too.

**Comment by ZePaiva** [comment]
Hey there, I'm having the same problem as @psmgeelen, has anyone found a fix yet?
I'm using Ubuntu 18.04 and Proton-6.5-GE-1

**Comment by doogie544** [comment]
@ZePaiva I'm not sure what you are trying to do?  You don't apply the mf-instalcab to GE's version of Proton.  The patches are already applied.  

I can say from my testing that GE 6.5 does not appear to work 100% with BL3.  I did start a new game to test it but did not watch the whole Marcus intro so Idk if it all works. I assumed that if it started it would work the whole way through. What I did notice is that when Lilith was supposed to pop up as  vision on my screen I could hear her voice but all that was showing was a grey spot on my screen where she was supposed to be.  Rolling back to GE 6.1-2 immediately fixed this issue.

It would appear that there are some regressions in GE 6.5.  I would recommend that you use 6.1-2 instead.

BUT DO NOT try to apply the mf-installcab fix to any GE version of proton.  At best it will do nothing, at worst it will break your prefix for the game.  I would recommend that you also delete  your existing prefix for the game if you have tried to install this script in the prefix while having it set to use GE's proton. It is located in

`~/.local/share/Steam/steamapps/compdata/397540`   just delete the entire folder

Note that the "Steam" folder varies by location a bit depending on your distro, that is the default location used by most.  If you installed it in Ubuntu via apt or apt-get directly from the repos  it is most likely in `~/.steam` in PopOs and Debian I believe it is install in a folder named `/.steam/debian-install/`   I'm not sure about any others.

I hope that this helps you get the game running but I think your post is a bit off-topic here as the script hosted here is not supposed to be applied to any GE Proton prefix and hence so is my answer.  Good Luck

**Comment by ZePaiva** [comment]
@doogie544 I tried proton GE without the fixes, regular proton (5.13) with the fixes (mf-install & mf-isntall cab, mf-install only, mf-installcab  only and mf-fix) and had no luck that is why I tried proton GE with the fixes and had no luck.

I followed the recipe from the Thanatos report in the proton page (If it does not display first in the BL3 page of proton I think this link can guide to the user and the report is there https://www.protondb.com/users/113675929) but kept getting errors and was not able to advance past video watching objectives.

Ultimately to advance in the game I edited the save file to skip the mission, so it is not an absolute game breaker but still bothers.

**Comment by psmgeelen** [comment]
@ZePaiva , I didnt find a fix..
